import { useState } from 'react'
import { motion } from 'framer-motion'
import {
  Sparkles,
  Brain,
  Target,
  Zap,
  GraduationCap,
  TrendingUp,
  MessageSquare,
  BarChart3,
  Bell,
  CheckCircle2,
  ArrowRight,
  Lightbulb,
  Award
} from 'lucide-react'
import { Sidebar } from '@/components/layout/Sidebar'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'

export function AIExamPrepPage() {
  const [email, setEmail] = useState('')
  const [isSubscribed, setIsSubscribed] = useState(false)
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false)

  // Toggle to show/hide additional content sections
  const showFullContent = false

  const handleNotifyMe = (e: React.FormEvent) => {
    e.preventDefault()
    // TODO: Implement email subscription logic
    setIsSubscribed(true)
    setTimeout(() => {
      setEmail('')
      setIsSubscribed(false)
    }, 3000)
  }

  const features = [
    {
      icon: Brain,
      title: 'AI-Generated Practice Questions',
      description: 'Unlimited adaptive questions tailored to your weak areas, generated by advanced AI understanding medical concepts.',
      color: 'from-blue-500 to-cyan-500',
      delay: 0.1
    },
    {
      icon: Target,
      title: 'Personalized Study Plans',
      description: 'Smart algorithms analyze your performance and create custom study schedules optimized for your exam timeline.',
      color: 'from-purple-500 to-pink-500',
      delay: 0.2
    },
    {
      icon: BarChart3,
      title: 'Advanced Analytics',
      description: 'Deep insights into your progress with predictive scoring, topic mastery tracking, and exam readiness indicators.',
      color: 'from-emerald-500 to-teal-500',
      delay: 0.3
    },
    {
      icon: Zap,
      title: 'Smart Flashcards',
      description: 'AI-powered spaced repetition that adapts to your memory curve, ensuring maximum retention with minimum time.',
      color: 'from-orange-500 to-amber-500',
      delay: 0.4
    }
  ]

  const stats = [
    { label: 'AI Models Trained', value: '4+', icon: Brain },
    { label: 'Question Bank Size', value: '2K+', icon: MessageSquare },
    { label: 'Success Rate', value: '94%', icon: Award },
    { label: 'Active Beta Testers', value: '2+', icon: TrendingUp }
  ]

  return (
    <div className="min-h-screen bg-background flex">
      <Sidebar
        isOpen={sidebarOpen}
        setIsOpen={setSidebarOpen}
        isCollapsed={sidebarCollapsed}
        setIsCollapsed={setSidebarCollapsed}
      />

      <main className="flex-1 overflow-auto">
        {/* Animated Background */}
        <div className="fixed inset-0 overflow-hidden pointer-events-none">
          {/* Gradient Orbs */}
          <motion.div
            className="absolute top-0 right-0 w-[500px] h-[500px] bg-gradient-to-br from-primary/20 to-secondary/20 rounded-full blur-3xl"
            animate={{
              scale: [1, 1.2, 1],
              opacity: [0.3, 0.5, 0.3],
            }}
            transition={{
              duration: 8,
              repeat: Infinity,
              ease: "easeInOut"
            }}
          />
          <motion.div
            className="absolute bottom-0 left-0 w-[600px] h-[600px] bg-gradient-to-tr from-secondary/20 to-primary/20 rounded-full blur-3xl"
            animate={{
              scale: [1.2, 1, 1.2],
              opacity: [0.2, 0.4, 0.2],
            }}
            transition={{
              duration: 10,
              repeat: Infinity,
              ease: "easeInOut"
            }}
          />

          {/* Floating Particles */}
          {[...Array(20)].map((_, i) => (
            <motion.div
              key={i}
              className="absolute w-1 h-1 bg-primary/30 rounded-full"
              style={{
                left: `${Math.random() * 100}%`,
                top: `${Math.random() * 100}%`,
              }}
              animate={{
                y: [0, -30, 0],
                opacity: [0, 1, 0],
              }}
              transition={{
                duration: 3 + Math.random() * 2,
                repeat: Infinity,
                delay: Math.random() * 2,
              }}
            />
          ))}
        </div>

        <div className="relative z-10 w-full">
          {/* Hero Section */}
          <section className="min-h-screen flex items-center justify-center px-6 lg:px-10 py-20">
            <div className="max-w-6xl mx-auto text-center">
              {/* Badge */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6 }}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 dark:bg-primary/20 border border-primary/20 mb-8"
              >
                <Sparkles className="w-4 h-4 text-primary" />
                <span className="text-sm font-medium text-primary">Coming Soon</span>
                <Sparkles className="w-4 h-4 text-primary" />
              </motion.div>

              {/* Main Heading */}
              <motion.h1
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.1 }}
                className="text-5xl sm:text-6xl lg:text-7xl font-bold mb-6 bg-gradient-to-r from-primary via-secondary to-primary bg-clip-text text-transparent"
                style={{ backgroundSize: '200% auto' }}
              >
                AI-Powered Exam Prep
              </motion.h1>

              <motion.p
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.2 }}
                className="text-xl sm:text-2xl text-muted-foreground max-w-3xl mx-auto mb-8"
              >
                The future of medical education is here. Prepare smarter, not harder, with AI that understands how you learn.
              </motion.p>

              {/* Animated Icon Grid */}
              <motion.div
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.8, delay: 0.3 }}
                className="flex items-center justify-center gap-6 mb-12 flex-wrap"
              >
                {[Brain, Lightbulb, Target, GraduationCap, Award].map((Icon, i) => (
                  <motion.div
                    key={i}
                    className="relative"
                    animate={{
                      y: [0, -10, 0],
                    }}
                    transition={{
                      duration: 2,
                      repeat: Infinity,
                      delay: i * 0.2,
                    }}
                  >
                    <div className="absolute inset-0 bg-gradient-to-r from-primary to-secondary rounded-2xl blur-xl opacity-50" />
                    <div className="relative bg-card/80 backdrop-blur-sm border border-primary/20 rounded-2xl p-4">
                      <Icon className="w-8 h-8 text-primary" />
                    </div>
                  </motion.div>
                ))}
              </motion.div>

              {/* Additional content - hidden until ready */}
              {showFullContent && (
              <>
              {/* Email Subscription */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.4 }}
                className="max-w-md mx-auto"
              >
                {!isSubscribed ? (
                  <form onSubmit={handleNotifyMe} className="relative">
                    <div className="flex gap-3">
                      <div className="flex-1 relative group">
                        <div className="absolute inset-0 bg-gradient-to-r from-primary to-secondary rounded-lg blur-lg opacity-0 group-hover:opacity-50 transition-opacity duration-300" />
                        <Input
                          type="email"
                          placeholder="Enter your email"
                          value={email}
                          onChange={(e) => setEmail(e.target.value)}
                          required
                          className="relative h-14 text-lg bg-card/80 backdrop-blur-sm border-primary/30 focus:border-primary"
                        />
                      </div>
                      <Button
                        type="submit"
                        size="lg"
                        className="h-14 px-8 bg-gradient-to-r from-primary to-secondary hover:shadow-lg hover:shadow-primary/50 transform hover:scale-105 transition-all duration-200"
                      >
                        <Bell className="w-5 h-5 mr-2" />
                        Notify Me
                      </Button>
                    </div>
                  </form>
                ) : (
                  <motion.div
                    initial={{ scale: 0.8, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    className="flex items-center justify-center gap-3 bg-emerald-500/10 border border-emerald-500/30 rounded-lg p-4"
                  >
                    <CheckCircle2 className="w-6 h-6 text-emerald-500" />
                    <span className="text-emerald-500 font-medium">You're on the list! We'll notify you when we launch.</span>
                  </motion.div>
                )}
              </motion.div>

              {/* Stats */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.5 }}
                className="grid grid-cols-2 lg:grid-cols-4 gap-6 mt-20 max-w-4xl mx-auto"
              >
                {stats.map((stat, i) => (
                  <motion.div
                    key={i}
                    whileHover={{ scale: 1.05, y: -5 }}
                    className="bg-card/60 backdrop-blur-sm border border-border/50 rounded-xl p-6 text-center group hover:border-primary/50 transition-colors duration-300"
                  >
                    <stat.icon className="w-8 h-8 mx-auto mb-3 text-primary group-hover:scale-110 transition-transform duration-300" />
                    <div className="text-3xl font-bold text-foreground mb-1">{stat.value}</div>
                    <div className="text-sm text-muted-foreground">{stat.label}</div>
                  </motion.div>
                ))}
              </motion.div>
              </>
              )}
            </div>
          </section>

          {/* Features Section and beyond - hidden until ready */}
          {showFullContent && (
          <>
          {/* Features Section */}
          <section className="px-6 lg:px-10 py-20 bg-card/30 backdrop-blur-sm">
            <div className="max-w-6xl mx-auto">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6 }}
                className="text-center mb-16"
              >
                <h2 className="text-4xl lg:text-5xl font-bold mb-4">
                  What's Coming
                </h2>
                <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
                  We're building the most advanced AI-powered exam preparation platform for medical students
                </p>
              </motion.div>

              <div className="grid md:grid-cols-2 gap-8">
                {features.map((feature, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, y: 30 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.6, delay: feature.delay }}
                    whileHover={{ scale: 1.02, y: -5 }}
                    className="group relative"
                  >
                    {/* Gradient Border Effect */}
                    <div className={`absolute inset-0 bg-gradient-to-r ${feature.color} opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-2xl blur-xl`}
                    />

                    {/* Card Content */}
                    <div className="relative bg-card/80 backdrop-blur-sm border border-border/50 rounded-2xl p-8 h-full group-hover:border-primary/50 transition-colors duration-300">
                      {/* Icon with Gradient Background */}
                      <div className="relative inline-flex mb-6">
                        <div className={`absolute inset-0 bg-gradient-to-r ${feature.color} rounded-2xl blur-lg opacity-50 group-hover:opacity-75 transition-opacity duration-300`} />
                        <div className="relative bg-card rounded-2xl p-4">
                          <feature.icon className="w-10 h-10 text-primary group-hover:scale-110 transition-transform duration-300" />
                        </div>
                      </div>

                      <h3 className="text-2xl font-bold mb-3 group-hover:text-primary transition-colors duration-300">
                        {feature.title}
                      </h3>
                      <p className="text-muted-foreground leading-relaxed mb-4">
                        {feature.description}
                      </p>

                      {/* Arrow Icon */}
                      <div className="flex items-center text-primary opacity-0 group-hover:opacity-100 transform translate-x-0 group-hover:translate-x-2 transition-all duration-300">
                        <span className="text-sm font-medium mr-2">Learn more</span>
                        <ArrowRight className="w-4 h-4" />
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          </section>

          {/* Timeline Section */}
          <section className="px-6 lg:px-10 py-20">
            <div className="max-w-4xl mx-auto">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6 }}
                className="text-center mb-16"
              >
                <h2 className="text-4xl lg:text-5xl font-bold mb-4">
                  Development Roadmap
                </h2>
                <p className="text-xl text-muted-foreground">
                  Track our progress as we build the future of medical exam preparation
                </p>
              </motion.div>

              <div className="space-y-8">
                {[
                  { phase: 'Q1 2026', title: 'Beta Launch', status: 'in-progress', description: 'Limited beta testing with 20 medical students' },
                  { phase: 'Q2 2026', title: 'AI Question Generation', status: 'upcoming', description: 'Advanced AI models for unlimited practice questions' },
                  { phase: 'Q3 2026', title: 'Performance Analytics', status: 'upcoming', description: 'Deep insights and predictive exam scoring' },
                  { phase: 'Q4 2026', title: 'Public Launch', status: 'upcoming', description: 'Full release with all features for everyone' },
                ].map((item, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, x: -30 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.6, delay: i * 0.1 }}
                    className="flex gap-6 items-start"
                  >
                    {/* Timeline Dot */}
                    <div className="flex flex-col items-center">
                      <div className={`w-12 h-12 rounded-full flex items-center justify-center ${
                        item.status === 'in-progress'
                          ? 'bg-gradient-to-r from-primary to-secondary animate-pulse'
                          : 'bg-card border-2 border-border'
                      }`}>
                        {item.status === 'in-progress' ? (
                          <Zap className="w-6 h-6 text-white" />
                        ) : (
                          <div className="w-3 h-3 rounded-full bg-muted" />
                        )}
                      </div>
                      {i < 3 && <div className="w-0.5 h-full bg-border mt-2" />}
                    </div>

                    {/* Content */}
                    <div className="flex-1 pb-12">
                      <div className="bg-card/60 backdrop-blur-sm border border-border/50 rounded-xl p-6 hover:border-primary/50 transition-colors duration-300">
                        <div className="flex items-center gap-3 mb-2">
                          <span className="text-sm font-medium text-primary">{item.phase}</span>
                          {item.status === 'in-progress' && (
                            <span className="text-xs px-2 py-1 rounded-full bg-primary/10 text-primary border border-primary/20">
                              In Progress
                            </span>
                          )}
                        </div>
                        <h3 className="text-xl font-bold mb-2">{item.title}</h3>
                        <p className="text-muted-foreground">{item.description}</p>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          </section>

          {/* CTA Section */}
          <section className="px-6 lg:px-10 py-20 bg-gradient-to-r from-primary/10 via-secondary/10 to-primary/10">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="max-w-4xl mx-auto text-center"
            >
              <div className="relative">
                {/* Glow Effect */}
                <div className="absolute inset-0 bg-gradient-to-r from-primary to-secondary rounded-3xl blur-3xl opacity-20" />

                {/* Card */}
                <div className="relative bg-card/80 backdrop-blur-sm border border-border/50 rounded-3xl p-12">
                  <GraduationCap className="w-16 h-16 mx-auto mb-6 text-primary" />
                  <h2 className="text-3xl lg:text-4xl font-bold mb-4">
                    Be the First to Know
                  </h2>
                  <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
                    Join our waitlist and get early access to the AI Exam Prep beta. Limited spots available.
                  </p>

                  {!isSubscribed ? (
                    <form onSubmit={handleNotifyMe} className="max-w-md mx-auto">
                      <div className="flex gap-3">
                        <Input
                          type="email"
                          placeholder="Your email address"
                          value={email}
                          onChange={(e) => setEmail(e.target.value)}
                          required
                          className="h-14 text-lg bg-background/50 backdrop-blur-sm border-primary/30"
                        />
                        <Button
                          type="submit"
                          size="lg"
                          className="h-14 px-8 bg-gradient-to-r from-primary to-secondary hover:shadow-xl hover:shadow-primary/50 transform hover:scale-105 transition-all duration-200"
                        >
                          <Sparkles className="w-5 h-5 mr-2" />
                          Get Early Access
                        </Button>
                      </div>
                    </form>
                  ) : (
                    <motion.div
                      initial={{ scale: 0.8, opacity: 0 }}
                      animate={{ scale: 1, opacity: 1 }}
                      className="flex items-center justify-center gap-3 bg-emerald-500/10 border border-emerald-500/30 rounded-lg p-4 max-w-md mx-auto"
                    >
                      <CheckCircle2 className="w-6 h-6 text-emerald-500" />
                      <span className="text-emerald-500 font-medium">Success! We'll notify you soon.</span>
                    </motion.div>
                  )}
                </div>
              </div>
            </motion.div>
          </section>
          </>
          )}
        </div>
      </main>
    </div>
  )
}
